---
- name: Create CTFd directory
  file:
    path: /opt/ctfd
    state: directory
    mode: '0755'

- name: Create CTFd subdirectories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /opt/ctfd/CTFd/logs
    - /opt/ctfd/CTFd/uploads

- name: Create Docker Compose file
  copy:
    src: docker-compose.yml
    dest: /opt/ctfd/docker-compose.yml
    mode: '0644'