---
- name: Install Docker via script
  shell: |
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
  args:
    creates: /usr/bin/docker

- name: Install Docker Compose via binary download
  get_url:
    url: "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
    owner: root
    group: root

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes